stages:
    - run

run_client:
    stage: run
    before-script:
        - cd client
        - npm install
    script:
        - npm run serve

run_server:
    stage: run
    script:
        - cd server
        - flask run
